# Generated by Django 4.1.7 on 2023-04-20 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("redirect", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="full_link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_link", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="short_link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_link", models.CharField(max_length=6)),
                (
                    "full_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="redirect.full_link",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="s_l",
        ),
    ]
