# Generated by Django 4.1.7 on 2023-05-13 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("redirect", "0002_full_link_short_link_delete_s_l"),
    ]

    operations = [
        migrations.AlterField(
            model_name="short_link",
            name="short_link",
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name="short_link",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
